### ISSUE TITLE
Make coaching page mobile-friendly

### ISSUE THREAD

**Issue by s314cy** [clicepfl/clic-website#94]
The list of coaches is wrongly displayed on mobile, it requires some CSS fixes.
The coach page isn't referenced in the pages menu on mobile.

**Comment by dialexo** [comment]
Also, you can pass the `tab = coaching` to the following macro call:

https://github.com/clicepfl/clic-website/blob/d603bb985fc132fd6a6bcba60f2152c9837f163e/src/pages/coaching/coaching-page-view.njk#L20

so that there's the `.current` class applied to the "Coaching" `li` menu element, it will add a white line below.
